spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/zeDelivery
    username: root
    password: totvs@123
    hikari:
      pool-name: lgpd-pool
  jpa:
    database-platform: org.hibernate.spatial.dialect.mysql.MySQLSpatialDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        temp:
          use_jdbc_metadata_defaults: false
  main:
    allow-bean-definition-overriding: true
    lazy-initialization: true
server:
  compression:
    enabled: true

